apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-app
  labels:
    app: backend
    env: dev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        env: dev
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: backend
          image: 495599741234.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_URL
              value: mongodb://mongodb-svc:27017/mern-todo?directConnection=true
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /started
              port: 5000
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 30
      terminationGracePeriodSeconds: 10