apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mern-app
  labels:
    role: frontend
    env: dev
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 495599741234.dkr.ecr.us-east-1.amazonaws.com/frontend
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://ignus.xyz/api/tasks"
        ports:
        - containerPort: 3000