apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mern-app
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==   # base64 for 'mongoadmin'
  mongo-root-password: c2VjcmV0cGFzcw==   # base64 for 'secretpass'

