apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-csi
provisioner: ebs.csi.aws.com
parameters:
  type: gp3    # recommended for new AWS EBS volumes
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
